### ISSUE TITLE
titlebar被statusbar遮住了

### ISSUE THREAD

**Issue by midiao** [jaeger23/StatusBarDemo#1]
楼主按照你的方法，结果titlebar被statusbar遮住了。我用的是Genymotion，Android 4.4.4 API 19的模拟器。
<img width="483" alt="e783bfb5-b6ba-4093-92da-88517ea2436f" src="https://cloud.githubusercontent.com/assets/2533555/17592801/4a574592-6016-11e6-8f94-e102bdb69236.png">

**Comment by laobie** [comment]
@midiao 方便贴一下代码么，或者加一下我qq 254158532

**Comment by midiao** [comment]
`rootView.setPadding(0, statusBarHeight, 0, 0);`这句代码中的rootView是`findViewById(android.R.id.content)`得到的。个人认为R.id.content是不包括titlebar的，所以设置它的padding是无法改变titlebar位置的。代码和你的示例代码是一样的。

**Comment by laobie** [comment]
你用的是那种布局，完整的代码贴上来，布局文件的也给一下，你的 titlebar 肯定实在 contentView 里面的，不怕麻烦请贴完整代码或者加我 qq

**Comment by laobie** [comment]
@midiao 你贴的那个 rootView.setPadding(0, statusBarHeight, 0, 0) 我的工具类中也没有= =你在哪看到的

**Comment by laobie** [comment]
@midiao 我看错了= =

**Comment by laobie** [comment]
@midiao  不过为嘛你认为 titlebar 不在 ContentView 里面呢？不可能不在 ContentView 里面啊

**Comment by midiao** [comment]
@laobie 楼主你好，大半夜还在回复真是辛苦了。
我的布局代码很简单：

``` xml
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/activity_main"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:background="@color/green"
    tools:context="org.lqynydyxf.addemo.MainActivity">
    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="@string/app_name" />
</LinearLayout>
```

我之所以认为titlebar不在contentview里是因为，我在查阅decorview的时候看到这幅图
<img width="479" alt="titlebar" src="https://cloud.githubusercontent.com/assets/2533555/17609938/e5ca25ee-606b-11e6-98c8-0771d6feda68.png">
根据我的测试（修改setPadding方法的第二个参数为100），结果如下图：
![demo](https://cloud.githubusercontent.com/assets/2533555/17610325/8cb80710-606f-11e6-9f00-56ceff40d8e0.png)，titlebar的位置并没有变化。
测试代码：

``` java
private void smoothSwitchScreen() {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP) {
            ViewGroup rootView = ((ViewGroup) findViewById(android.R.id.content));
            int resourceId = getResources().getIdentifier("status_bar_height", "dimen", "android");
            int statusBarHeight = getResources().getDimensionPixelSize(resourceId);
            rootView.setPadding(0, 100, 0, 0);
            getWindow().addFlags(WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN);
            getWindow().addFlags(WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS);
        }
    }
```

**Comment by midiao** [comment]
@laobie 是否我对titlebar的理解出错了？我理解的titlebar就是
![titlebar2](https://cloud.githubusercontent.com/assets/2533555/17610432/6dd6b386-6070-11e6-86f5-c71a33183cf1.png)，contentView就是titlebar下面的部分。

**Comment by laobie** [comment]
@midiao 看到你的回复了，你应该使用的还是 ActionBar， ActionBar 并不在 ContentView 里面，而是在 decorView 里面，而现在基本使用 Toolbar 了，Toolbar 是在 ContentView 里面的

**Comment by laobie** [comment]
@midiao 我发现问题了= =你应该在 setContentView 之前调用这个切换全屏的方法，而不是在其之后。。。

**Comment by midiao** [comment]
@laobie 博主，按照你的说法使用Toolbar替换ActionBar之后，然后做了个实验，确实如你所说Toobar是在ContentView里面的。多谢～
